#!/bin/sh

PARA_PREFIX="mpirun -n 8"
PARA_POSTFIX=""
#PARA_POSTFIX="-nk 4 -nd 1 -nb 1 -nt 1"
BIN_DIR=""

$PARA_PREFIX  pw.x  <  al.scf.in  > al.scf.out
$PARA_PREFIX  pw.x  <  al.dos1.in > al.dos1.out
$PARA_PREFIX  dos.x <  al.dos2.in > al.dos2.out

